language: r
warnings_are_errors: true
sudo: false

#addons:
#    apt:
#        packages:
#            - libgeos++-dev

matrix:
    include:
        - r: release
          env: DEPS=cran
          os: linux
        - r: release
          env: DEPS=cran
          os: osx
        - r: oldrel
          env: DEPS=cran
          os: linux
        - r: oldrel
          env: DEPS=cran
          os: osx
          #- r: devel
          #env: DEPS=cran
          #os: linux
          #- r: devel
          #env: DEPS=cran
          #os: osx

r_binary_packages:
    - rgeos

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
      - jimhester/covr

after_success:
      - Rscript -e 'covr::codecov()'
