language: r
warnings_are_errors: true
sudo: required

#addons:
#    apt:
#        packages:
#            - libgeos-dev
# NOTE: libgeo++-dev not on current travis-ci white list for container-based

before_install:
    - sudo apt-get install libgeos++-dev

matrix:
    include:
        - r: release
          env: DEPS=cran
          os: linux
        - r: release
          env: DEPS=cran
          os: osx
        - r: oldrel
          env: DEPS=cran
          os: linux
        - r: oldrel
          env: DEPS=cran
          os: osx
          #- r: devel
          #env: DEPS=cran
          #os: linux
          #- r: devel
          #env: DEPS=cran
          #os: osx

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
      - jimhester/covr

after_success:
      - Rscript -e 'covr::codecov()'
